### fetch all users
GET {{api_url}}/api/user HTTP/1.1
Content-Type: application/json
authorization: {{token}}

### fetch user with id
GET {{api_url}}/api/user/d9d5330c-62a3-427e-9aad-a749a29eceeb HTTP/1.1
Content-Type: application/json
authorization: {{token}}

### fetch user with name
GET {{api_url}}/api/user/search/b HTTP/1.1
Content-Type: application/json
authorization: {{token}}

### register
POST {{api_url}}/api/auth/register
Content-Type: application/json

{
    "name" : "brad",
    "email" : "brad@email.com",
    "password" : "brad",
    "phone": "1234567",
    "bloodGroup" : "AB+",
    "gender": "male",
    "location" : {
        "latitude" : 23.7258109,
        "longitude" : 90.3908448,
        "display_name": "Titumir Hall, BUET"
    }
}

### login
POST {{api_url}}/api/auth/login
Content-Type: application/json

{
    "email" : "m",
    "password" : "masum123"
}

### blood post
POST {{api_url}}/api/post/blood-post/
Content-Type: application/json
authorization: {{token}}

{
   "blood_group":"O+",
   "amount":1,
   "location":{
      "display_name":"bye",
      "latitude":15.526,
      "longitude":36.35
   },
   "contact":"235468778965",
   "due_time":"2022-02-20",
   "additional_info":"{\"text\": \"need emergency\"}"
}

### blood post by id
GET {{api_url}}/api/post/blood-post/ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92
Content-Type: application/json
authorization: {{token}}

### all blood post
GET {{api_url}}/api/post/blood-post/
Content-Type: application/json
authorization: {{token}}

### comment create
POST {{api_url}}/api/comment/
Content-Type: application/json
authorization: {{token}}

{
  "post_id":"ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92",
  "text": "what happened"
}

### comment get
GET {{api_url}}/api/comment/ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92
Content-Type: application/json
authorization: {{token}}


### post react
POST {{api_url}}/api/react/post
Content-Type: application/json
authorization: {{token}}

{
  "post_id":"ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92"
}


###  get react

GET {{api_url}}/api/react/post/ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92
Content-Type: application/json
authorization: {{token}}

###  undo react
DELETE {{api_url}}/api/react/post/ba46e5ac-89fa-4ada-9b1d-3b862b6d9f92
Content-Type: application/json
authorization: {{token}}


### get messages
GET {{api_url}}/api/message/e4c78117-4493-4d2d-a3a1-6f21306d897e
Content-Type: application/json
authorization: {{token}}


### get chat list
GET {{api_url}}/api/message
Content-Type: application/json
authorization: {{token}}

### create donation
POST {{api_url}}/api/donation
Content-Type: application/json
authorization: {{token}}

{
  "location":{
    "display_name":"bye",
    "latitude":15.526,
    "longitude":36.35
  },
  "donation_time": "2022-02-20"
}


### get all notification
GET {{api_url}}/api/notification
Content-Type: application/json
authorization: {{token}}