### fetch all users
GET http://localhost:3000/api/user HTTP/1.1

### fetch user with id
GET http://localhost:3000/api/user/d9d5330c-62a3-427e-9aad-a749a29eceeb HTTP/1.1

### register
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
    "name" : "masum2",
    "email" : "masum2@email.com",
    "password" : "masum2",
    "phoneNumber": "1234567",
    "bloodGroup" : "AB+",
    "gender": "male",
    "location" : {
        "latitude" : 23.7258109,
        "longitude" : 90.3908448,
        "text": "Titumir Hall, BUET"
    }
}

### login
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "email" : "masum4@email.com",
    "password" : "masum"
}


